# Generated by Django 5.1.1 on 2024-10-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('design_image', models.ImageField(upload_to='images/')),
                ('design_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
