# Generated by Django 5.1.1 on 2024-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_phone',
            field=models.CharField(max_length=12),
        ),
    ]
