# Generated by Django 5.1.1 on 2024-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerprofile_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
